npm link @angular/animations@~8.2.7
npm link @angular/common@~8.2.7
npm link @angular/compiler@~8.2.7
npm link @angular/core@~8.2.7
npm link @angular/forms@~8.2.7
npm link @angular/platform-browser@~8.2.7
npm link @angular/platform-browser-dynamic@~8.2.7
npm link @angular/router@~8.2.7
npm link @fortawesome/angular-fontawesome@^0.6.0
npm link @fortawesome/fontawesome-svg-core@^1.2.27
npm link @fortawesome/free-brands-svg-icons@^5.12.1
npm link @fortawesome/free-regular-svg-icons@^5.12.1
npm link @fortawesome/free-solid-svg-icons@^5.12.1
npm link @fortawesome/fontawesome-common-types
npm link @ng-bootstrap/ng-bootstrap@^5.2.1
npm link bootstrap@^4.4.1
npm link jquery@^3.4.1
npm link ngx-scrollreveal@^3.0.0
npm link ngx-slick-carousel@^0.4.7
npm link popper.js@^1.16.1
npm link rxjs@~6.4.0
npm link scrollreveal@^4.0.5
npm link slick-carousel@^1.8.1
npm link tslib@^1.10.0
npm link zone.js@~0.9.1

npm link @angular-devkit/build-angular@~0.803.5
npm link @angular/cli@~8.3.5
npm link @angular/compiler-cli@~8.2.7
npm link @angular/language-service@~8.2.7
npm link @types/node@~8.9.4
npm link @types/jasmine@~3.3.8
npm link @types/jasminewd2@~2.0.3
npm link codelyzer@^5.0.0
npm link jasmine-core@~3.4.0
npm link jasmine-spec-reporter@~4.2.1
npm link karma@~4.1.0
npm link karma-chrome-launcher@~2.2.0
npm link karma-coverage-istanbul-reporter@~2.0.1
npm link karma-jasmine@~2.0.1
npm link karma-jasmine-html-reporter@^1.4.0
npm link protractor@~5.4.0
npm link ts-node@~7.0.0
npm link tslint@~5.15.0
npm link typescript@~3.5.3