npm install -g @angular/animations@~8.2.7
npm install -g @angular/common@~8.2.7
npm install -g @angular/compiler@~8.2.7
npm install -g @angular/core@~8.2.7
npm install -g @angular/forms@~8.2.7
npm install -g @angular/platform-browser@~8.2.7
npm install -g @angular/platform-browser-dynamic@~8.2.7
npm install -g @angular/router@~8.2.7
npm install -g @fortawesome/angular-fontawesome@^0.6.0
npm install -g @fortawesome/fontawesome-svg-core@^1.2.27
npm install -g @fortawesome/free-brands-svg-icons@^5.12.1
npm install -g @fortawesome/free-regular-svg-icons@^5.12.1
npm install -g @fortawesome/free-solid-svg-icons@^5.12.1
npm install -g @fortawesome/fontawesome-common-types
npm install -g @ng-bootstrap/ng-bootstrap@^5.2.1
npm install -g bootstrap@^4.4.1
npm install -g jquery@^3.4.1
npm install -g ngx-scrollreveal@^3.0.0
npm install -g ngx-slick-carousel@^0.4.7
npm install -g popper.js@^1.16.1
npm install -g rxjs@~6.4.0
npm install -g scrollreveal@^4.0.5
npm install -g slick-carousel@^1.8.1
npm install -g tslib@^1.10.0
npm install -g zone.js@~0.9.1

npm install -g @angular-devkit/build-angular@~0.803.5
npm install -g @angular/cli@~8.3.5
npm install -g @angular/compiler-cli@~8.2.7
npm install -g @angular/language-service@~8.2.7
npm install -g @types/node@~8.9.4
npm install -g @types/jasmine@~3.3.8
npm install -g @types/jasminewd2@~2.0.3
npm install -g codelyzer@^5.0.0
npm install -g jasmine-core@~3.4.0
npm install -g jasmine-spec-reporter@~4.2.1
npm install -g karma@~4.1.0
npm install -g karma-chrome-launcher@~2.2.0
npm install -g karma-coverage-istanbul-reporter@~2.0.1
npm install -g karma-jasmine@~2.0.1
npm install -g karma-jasmine-html-reporter@^1.4.0
npm install -g protractor@~5.4.0
npm install -g ts-node@~7.0.0
npm install -g tslint@~5.15.0
npm install -g typescript@~3.5.3